// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/env.proto

package sphere_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Response for Sphere info.
type InfoResponse struct {
	// Version of Sphere running.
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{0}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Request to create an environment
type CreateEnvRequest struct {
	// Name of the environment model.
	ModelName            string   `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEnvRequest) Reset()         { *m = CreateEnvRequest{} }
func (m *CreateEnvRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEnvRequest) ProtoMessage()    {}
func (*CreateEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{1}
}

func (m *CreateEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEnvRequest.Unmarshal(m, b)
}
func (m *CreateEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEnvRequest.Marshal(b, m, deterministic)
}
func (m *CreateEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEnvRequest.Merge(m, src)
}
func (m *CreateEnvRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEnvRequest.Size(m)
}
func (m *CreateEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEnvRequest proto.InternalMessageInfo

func (m *CreateEnvRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

// Response from creating an environment.
type CreateEnvResponse struct {
	// Shape of the observation.
	ObservationShape []int32 `protobuf:"varint,1,rep,packed,name=observation_shape,json=observationShape,proto3" json:"observation_shape,omitempty"`
	// Number of actions.
	NumActions int32 `protobuf:"varint,2,opt,name=num_actions,json=numActions,proto3" json:"num_actions,omitempty"`
	// Maximum number of episode steps.
	MaxEpisodeSteps      int32    `protobuf:"varint,3,opt,name=max_episode_steps,json=maxEpisodeSteps,proto3" json:"max_episode_steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEnvResponse) Reset()         { *m = CreateEnvResponse{} }
func (m *CreateEnvResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEnvResponse) ProtoMessage()    {}
func (*CreateEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{2}
}

func (m *CreateEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEnvResponse.Unmarshal(m, b)
}
func (m *CreateEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEnvResponse.Marshal(b, m, deterministic)
}
func (m *CreateEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEnvResponse.Merge(m, src)
}
func (m *CreateEnvResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEnvResponse.Size(m)
}
func (m *CreateEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEnvResponse proto.InternalMessageInfo

func (m *CreateEnvResponse) GetObservationShape() []int32 {
	if m != nil {
		return m.ObservationShape
	}
	return nil
}

func (m *CreateEnvResponse) GetNumActions() int32 {
	if m != nil {
		return m.NumActions
	}
	return 0
}

func (m *CreateEnvResponse) GetMaxEpisodeSteps() int32 {
	if m != nil {
		return m.MaxEpisodeSteps
	}
	return 0
}

// Request to list environments.
type ListEnvRequest struct {
	// Limit the number of environments returned.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Where to start returning list from.
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEnvRequest) Reset()         { *m = ListEnvRequest{} }
func (m *ListEnvRequest) String() string { return proto.CompactTextString(m) }
func (*ListEnvRequest) ProtoMessage()    {}
func (*ListEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{3}
}

func (m *ListEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEnvRequest.Unmarshal(m, b)
}
func (m *ListEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEnvRequest.Marshal(b, m, deterministic)
}
func (m *ListEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEnvRequest.Merge(m, src)
}
func (m *ListEnvRequest) XXX_Size() int {
	return xxx_messageInfo_ListEnvRequest.Size(m)
}
func (m *ListEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEnvRequest proto.InternalMessageInfo

func (m *ListEnvRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListEnvRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// Response from listing environments.
type ListEnvResponse struct {
	// List of environments.
	Envs                 []*Environment `protobuf:"bytes,1,rep,name=envs,proto3" json:"envs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListEnvResponse) Reset()         { *m = ListEnvResponse{} }
func (m *ListEnvResponse) String() string { return proto.CompactTextString(m) }
func (*ListEnvResponse) ProtoMessage()    {}
func (*ListEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{4}
}

func (m *ListEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEnvResponse.Unmarshal(m, b)
}
func (m *ListEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEnvResponse.Marshal(b, m, deterministic)
}
func (m *ListEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEnvResponse.Merge(m, src)
}
func (m *ListEnvResponse) XXX_Size() int {
	return xxx_messageInfo_ListEnvResponse.Size(m)
}
func (m *ListEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEnvResponse proto.InternalMessageInfo

func (m *ListEnvResponse) GetEnvs() []*Environment {
	if m != nil {
		return m.Envs
	}
	return nil
}

// Request to get an environment.
type GetEnvRequest struct {
	// ID of the environment.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEnvRequest) Reset()         { *m = GetEnvRequest{} }
func (m *GetEnvRequest) String() string { return proto.CompactTextString(m) }
func (*GetEnvRequest) ProtoMessage()    {}
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{5}
}

func (m *GetEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEnvRequest.Unmarshal(m, b)
}
func (m *GetEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEnvRequest.Marshal(b, m, deterministic)
}
func (m *GetEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEnvRequest.Merge(m, src)
}
func (m *GetEnvRequest) XXX_Size() int {
	return xxx_messageInfo_GetEnvRequest.Size(m)
}
func (m *GetEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEnvRequest proto.InternalMessageInfo

func (m *GetEnvRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response from getting an environment.
type GetEnvResponse struct {
	// Environment data.
	Env                  *Environment `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEnvResponse) Reset()         { *m = GetEnvResponse{} }
func (m *GetEnvResponse) String() string { return proto.CompactTextString(m) }
func (*GetEnvResponse) ProtoMessage()    {}
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{6}
}

func (m *GetEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEnvResponse.Unmarshal(m, b)
}
func (m *GetEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEnvResponse.Marshal(b, m, deterministic)
}
func (m *GetEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEnvResponse.Merge(m, src)
}
func (m *GetEnvResponse) XXX_Size() int {
	return xxx_messageInfo_GetEnvResponse.Size(m)
}
func (m *GetEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEnvResponse proto.InternalMessageInfo

func (m *GetEnvResponse) GetEnv() *Environment {
	if m != nil {
		return m.Env
	}
	return nil
}

// Request to list models.
type ListModelsRequest struct {
	// Limit the number of models returned.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Where to start returning list from.
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{7}
}

func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListModelsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// Response from listing models.
type ListModelsResponse struct {
	// List of models.
	Models               []*Model `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsResponse) Reset()         { *m = ListModelsResponse{} }
func (m *ListModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListModelsResponse) ProtoMessage()    {}
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{8}
}

func (m *ListModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsResponse.Unmarshal(m, b)
}
func (m *ListModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsResponse.Merge(m, src)
}
func (m *ListModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListModelsResponse.Size(m)
}
func (m *ListModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsResponse proto.InternalMessageInfo

func (m *ListModelsResponse) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

// Response from resetting an environment.
type ResetEnvRequest struct {
	// ID of the environment.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetEnvRequest) Reset()         { *m = ResetEnvRequest{} }
func (m *ResetEnvRequest) String() string { return proto.CompactTextString(m) }
func (*ResetEnvRequest) ProtoMessage()    {}
func (*ResetEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{9}
}

func (m *ResetEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetEnvRequest.Unmarshal(m, b)
}
func (m *ResetEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetEnvRequest.Marshal(b, m, deterministic)
}
func (m *ResetEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetEnvRequest.Merge(m, src)
}
func (m *ResetEnvRequest) XXX_Size() int {
	return xxx_messageInfo_ResetEnvRequest.Size(m)
}
func (m *ResetEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetEnvRequest proto.InternalMessageInfo

func (m *ResetEnvRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response from resetting an environment.
type ResetEnvResponse struct {
	// Observation of environment after resetting.
	Observation          *Observation `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResetEnvResponse) Reset()         { *m = ResetEnvResponse{} }
func (m *ResetEnvResponse) String() string { return proto.CompactTextString(m) }
func (*ResetEnvResponse) ProtoMessage()    {}
func (*ResetEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{10}
}

func (m *ResetEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetEnvResponse.Unmarshal(m, b)
}
func (m *ResetEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetEnvResponse.Marshal(b, m, deterministic)
}
func (m *ResetEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetEnvResponse.Merge(m, src)
}
func (m *ResetEnvResponse) XXX_Size() int {
	return xxx_messageInfo_ResetEnvResponse.Size(m)
}
func (m *ResetEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetEnvResponse proto.InternalMessageInfo

func (m *ResetEnvResponse) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

// Request to step in an environment.
type StepEnvRequest struct {
	// ID of the environment.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Step with given value.
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepEnvRequest) Reset()         { *m = StepEnvRequest{} }
func (m *StepEnvRequest) String() string { return proto.CompactTextString(m) }
func (*StepEnvRequest) ProtoMessage()    {}
func (*StepEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{11}
}

func (m *StepEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepEnvRequest.Unmarshal(m, b)
}
func (m *StepEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepEnvRequest.Marshal(b, m, deterministic)
}
func (m *StepEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepEnvRequest.Merge(m, src)
}
func (m *StepEnvRequest) XXX_Size() int {
	return xxx_messageInfo_StepEnvRequest.Size(m)
}
func (m *StepEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StepEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StepEnvRequest proto.InternalMessageInfo

func (m *StepEnvRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StepEnvRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Response from stepping in an environment.
type StepEnvResponse struct {
	// Observation after step.
	Observation *Observation `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	// Reware after step.
	Reward float32 `protobuf:"fixed32,2,opt,name=reward,proto3" json:"reward,omitempty"`
	// Observation for next episode.
	NextEpisode          *Observation `protobuf:"bytes,3,opt,name=next_episode,json=nextEpisode,proto3" json:"next_episode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StepEnvResponse) Reset()         { *m = StepEnvResponse{} }
func (m *StepEnvResponse) String() string { return proto.CompactTextString(m) }
func (*StepEnvResponse) ProtoMessage()    {}
func (*StepEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{12}
}

func (m *StepEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepEnvResponse.Unmarshal(m, b)
}
func (m *StepEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepEnvResponse.Marshal(b, m, deterministic)
}
func (m *StepEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepEnvResponse.Merge(m, src)
}
func (m *StepEnvResponse) XXX_Size() int {
	return xxx_messageInfo_StepEnvResponse.Size(m)
}
func (m *StepEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StepEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StepEnvResponse proto.InternalMessageInfo

func (m *StepEnvResponse) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

func (m *StepEnvResponse) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *StepEnvResponse) GetNextEpisode() *Observation {
	if m != nil {
		return m.NextEpisode
	}
	return nil
}

// Request to watch an environment.
type WatchEnvRequest struct {
	// ID of the environment.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchEnvRequest) Reset()         { *m = WatchEnvRequest{} }
func (m *WatchEnvRequest) String() string { return proto.CompactTextString(m) }
func (*WatchEnvRequest) ProtoMessage()    {}
func (*WatchEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{13}
}

func (m *WatchEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchEnvRequest.Unmarshal(m, b)
}
func (m *WatchEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchEnvRequest.Marshal(b, m, deterministic)
}
func (m *WatchEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchEnvRequest.Merge(m, src)
}
func (m *WatchEnvRequest) XXX_Size() int {
	return xxx_messageInfo_WatchEnvRequest.Size(m)
}
func (m *WatchEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchEnvRequest proto.InternalMessageInfo

func (m *WatchEnvRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response from watching an environment.
type WatchEnvResponse struct {
	// Observation after step.
	Observation *Observation `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	// Reware after step.
	Reward float32 `protobuf:"fixed32,2,opt,name=reward,proto3" json:"reward,omitempty"`
	// Observation for next episode.
	NextEpisode          *Observation `protobuf:"bytes,3,opt,name=next_episode,json=nextEpisode,proto3" json:"next_episode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WatchEnvResponse) Reset()         { *m = WatchEnvResponse{} }
func (m *WatchEnvResponse) String() string { return proto.CompactTextString(m) }
func (*WatchEnvResponse) ProtoMessage()    {}
func (*WatchEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{14}
}

func (m *WatchEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchEnvResponse.Unmarshal(m, b)
}
func (m *WatchEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchEnvResponse.Marshal(b, m, deterministic)
}
func (m *WatchEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchEnvResponse.Merge(m, src)
}
func (m *WatchEnvResponse) XXX_Size() int {
	return xxx_messageInfo_WatchEnvResponse.Size(m)
}
func (m *WatchEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchEnvResponse proto.InternalMessageInfo

func (m *WatchEnvResponse) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

func (m *WatchEnvResponse) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *WatchEnvResponse) GetNextEpisode() *Observation {
	if m != nil {
		return m.NextEpisode
	}
	return nil
}

// Request to interact in an environment.
type InteractEnvRequest struct {
	// ID of the environment.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Step with given value.
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteractEnvRequest) Reset()         { *m = InteractEnvRequest{} }
func (m *InteractEnvRequest) String() string { return proto.CompactTextString(m) }
func (*InteractEnvRequest) ProtoMessage()    {}
func (*InteractEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{15}
}

func (m *InteractEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractEnvRequest.Unmarshal(m, b)
}
func (m *InteractEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractEnvRequest.Marshal(b, m, deterministic)
}
func (m *InteractEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractEnvRequest.Merge(m, src)
}
func (m *InteractEnvRequest) XXX_Size() int {
	return xxx_messageInfo_InteractEnvRequest.Size(m)
}
func (m *InteractEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InteractEnvRequest proto.InternalMessageInfo

func (m *InteractEnvRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InteractEnvRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Response from interacting in an environment.
type InteractEnvResponse struct {
	// Observation after step.
	Observation *Observation `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	// Reware after step.
	Reward float32 `protobuf:"fixed32,2,opt,name=reward,proto3" json:"reward,omitempty"`
	// Observation for next episode.
	NextEpisode          *Observation `protobuf:"bytes,3,opt,name=next_episode,json=nextEpisode,proto3" json:"next_episode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InteractEnvResponse) Reset()         { *m = InteractEnvResponse{} }
func (m *InteractEnvResponse) String() string { return proto.CompactTextString(m) }
func (*InteractEnvResponse) ProtoMessage()    {}
func (*InteractEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{16}
}

func (m *InteractEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractEnvResponse.Unmarshal(m, b)
}
func (m *InteractEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractEnvResponse.Marshal(b, m, deterministic)
}
func (m *InteractEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractEnvResponse.Merge(m, src)
}
func (m *InteractEnvResponse) XXX_Size() int {
	return xxx_messageInfo_InteractEnvResponse.Size(m)
}
func (m *InteractEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InteractEnvResponse proto.InternalMessageInfo

func (m *InteractEnvResponse) GetObservation() *Observation {
	if m != nil {
		return m.Observation
	}
	return nil
}

func (m *InteractEnvResponse) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *InteractEnvResponse) GetNextEpisode() *Observation {
	if m != nil {
		return m.NextEpisode
	}
	return nil
}

// Observation of environment.
type Observation struct {
	// Data from environment.
	Data []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	// Shape of environment.
	Shape                []int32  `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Observation) Reset()         { *m = Observation{} }
func (m *Observation) String() string { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()    {}
func (*Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{17}
}

func (m *Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observation.Unmarshal(m, b)
}
func (m *Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observation.Marshal(b, m, deterministic)
}
func (m *Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observation.Merge(m, src)
}
func (m *Observation) XXX_Size() int {
	return xxx_messageInfo_Observation.Size(m)
}
func (m *Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_Observation proto.InternalMessageInfo

func (m *Observation) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Observation) GetShape() []int32 {
	if m != nil {
		return m.Shape
	}
	return nil
}

// Environment agents can interact with.
type Environment struct {
	// Name of the model used to build the environment.
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// ID of the environment.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{18}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *Environment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Model environments can be created from.
type Model struct {
	// Name of the model.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the model.
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{19}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Empty message.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_afb5d2a87359ebba, []int{20}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InfoResponse)(nil), "sphere.api.InfoResponse")
	proto.RegisterType((*CreateEnvRequest)(nil), "sphere.api.CreateEnvRequest")
	proto.RegisterType((*CreateEnvResponse)(nil), "sphere.api.CreateEnvResponse")
	proto.RegisterType((*ListEnvRequest)(nil), "sphere.api.ListEnvRequest")
	proto.RegisterType((*ListEnvResponse)(nil), "sphere.api.ListEnvResponse")
	proto.RegisterType((*GetEnvRequest)(nil), "sphere.api.GetEnvRequest")
	proto.RegisterType((*GetEnvResponse)(nil), "sphere.api.GetEnvResponse")
	proto.RegisterType((*ListModelsRequest)(nil), "sphere.api.ListModelsRequest")
	proto.RegisterType((*ListModelsResponse)(nil), "sphere.api.ListModelsResponse")
	proto.RegisterType((*ResetEnvRequest)(nil), "sphere.api.ResetEnvRequest")
	proto.RegisterType((*ResetEnvResponse)(nil), "sphere.api.ResetEnvResponse")
	proto.RegisterType((*StepEnvRequest)(nil), "sphere.api.StepEnvRequest")
	proto.RegisterType((*StepEnvResponse)(nil), "sphere.api.StepEnvResponse")
	proto.RegisterType((*WatchEnvRequest)(nil), "sphere.api.WatchEnvRequest")
	proto.RegisterType((*WatchEnvResponse)(nil), "sphere.api.WatchEnvResponse")
	proto.RegisterType((*InteractEnvRequest)(nil), "sphere.api.InteractEnvRequest")
	proto.RegisterType((*InteractEnvResponse)(nil), "sphere.api.InteractEnvResponse")
	proto.RegisterType((*Observation)(nil), "sphere.api.Observation")
	proto.RegisterType((*Environment)(nil), "sphere.api.Environment")
	proto.RegisterType((*Model)(nil), "sphere.api.Model")
	proto.RegisterType((*Empty)(nil), "sphere.api.Empty")
}

func init() { proto.RegisterFile("api/env.proto", fileDescriptor_afb5d2a87359ebba) }

var fileDescriptor_afb5d2a87359ebba = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xce, 0x2e, 0xb4, 0xc0, 0x29, 0xfd, 0x1b, 0x14, 0xea, 0x4a, 0x01, 0xe7, 0xaa, 0x62, 0x6c,
	0x03, 0x26, 0x1a, 0xab, 0x62, 0x88, 0x69, 0x0c, 0x89, 0x68, 0xb2, 0x44, 0xbd, 0x32, 0xcd, 0xd0,
	0x1d, 0x60, 0x93, 0xee, 0xec, 0xba, 0x33, 0x5d, 0x31, 0xc6, 0x1b, 0xaf, 0xf5, 0xca, 0x17, 0xd0,
	0xc4, 0x37, 0xf2, 0x15, 0x7c, 0x10, 0x33, 0xb3, 0xd3, 0x76, 0xb6, 0x29, 0x35, 0xea, 0x0d, 0x77,
	0x3d, 0xe7, 0x7c, 0xe7, 0x3b, 0x3f, 0xb3, 0xf3, 0x4d, 0xa1, 0x48, 0x22, 0xbf, 0x45, 0x59, 0xd2,
	0x8c, 0xe2, 0x50, 0x84, 0x08, 0x78, 0x74, 0x46, 0x63, 0xda, 0x24, 0x91, 0xef, 0xac, 0x9f, 0x86,
	0xe1, 0x69, 0x9f, 0xb6, 0x24, 0x82, 0x30, 0x16, 0x0a, 0x22, 0xfc, 0x90, 0xf1, 0x14, 0x89, 0x1b,
	0xb0, 0x7c, 0xc0, 0x4e, 0x42, 0x97, 0xf2, 0x28, 0x64, 0x9c, 0xa2, 0x1a, 0x2c, 0x24, 0x34, 0xe6,
	0x7e, 0xc8, 0x6a, 0xd6, 0x96, 0xd5, 0x58, 0x72, 0x87, 0x26, 0xde, 0x81, 0xca, 0x93, 0x98, 0x12,
	0x41, 0x3b, 0x2c, 0x71, 0xe9, 0xdb, 0x01, 0xe5, 0x02, 0xd5, 0x01, 0x82, 0xd0, 0xa3, 0xfd, 0x2e,
	0x23, 0x01, 0xd5, 0x09, 0x4b, 0xca, 0xf3, 0x9c, 0x04, 0x14, 0x7f, 0xb1, 0xa0, 0x6a, 0xe4, 0xe8,
	0x12, 0xb7, 0xa0, 0x1a, 0x1e, 0x73, 0x1a, 0x27, 0xaa, 0x91, 0x2e, 0x3f, 0x23, 0x91, 0xcc, 0x9d,
	0x6b, 0xe4, 0xdc, 0x8a, 0x11, 0x38, 0x92, 0x7e, 0xb4, 0x09, 0x05, 0x36, 0x08, 0xba, 0xa4, 0xa7,
	0x9a, 0xae, 0xd9, 0x5b, 0x56, 0x23, 0xe7, 0x02, 0x1b, 0x04, 0xfb, 0xa9, 0x07, 0x6d, 0x43, 0x35,
	0x20, 0xe7, 0x5d, 0x1a, 0xf9, 0x3c, 0xf4, 0x68, 0x97, 0x0b, 0x1a, 0xf1, 0xda, 0x9c, 0x82, 0x95,
	0x03, 0x72, 0xde, 0x49, 0xfd, 0x47, 0xd2, 0x8d, 0xf7, 0xa0, 0xf4, 0xcc, 0xe7, 0xc2, 0x18, 0xe0,
	0x0a, 0xe4, 0xfa, 0x7e, 0xe0, 0x0b, 0xd5, 0x7b, 0xce, 0x4d, 0x0d, 0xb4, 0x0a, 0xf9, 0xf0, 0xe4,
	0x84, 0x53, 0xa1, 0xeb, 0x69, 0x0b, 0xef, 0x41, 0x79, 0x94, 0x3f, 0x1a, 0x66, 0x9e, 0xb2, 0x84,
	0xab, 0xfe, 0x0b, 0xbb, 0x6b, 0xcd, 0xf1, 0xe2, 0x9b, 0x1d, 0x96, 0xf8, 0x71, 0xc8, 0x02, 0xca,
	0x84, 0xab, 0x40, 0x78, 0x13, 0x8a, 0x4f, 0xa9, 0x59, 0xbe, 0x04, 0xb6, 0xef, 0xe9, 0xbd, 0xd9,
	0xbe, 0x87, 0x1f, 0x40, 0x69, 0x08, 0xd0, 0xfc, 0x37, 0x61, 0x8e, 0xb2, 0x44, 0x41, 0x66, 0xd0,
	0x4b, 0x0c, 0xde, 0x87, 0xaa, 0xec, 0xee, 0x50, 0xae, 0x9f, 0xff, 0xdb, 0x80, 0x8f, 0x01, 0x99,
	0x14, 0xa3, 0x1e, 0xf2, 0xea, 0x4c, 0x87, 0x53, 0x56, 0xcd, 0x36, 0x14, 0xd6, 0xd5, 0x00, 0x7c,
	0x03, 0xca, 0x2e, 0xe5, 0x33, 0x67, 0x3c, 0x84, 0xca, 0x18, 0xa2, 0x2b, 0xdc, 0x87, 0x82, 0x71,
	0xf2, 0xd3, 0xa6, 0x7d, 0x31, 0x0e, 0xbb, 0x26, 0x16, 0xdf, 0x85, 0x92, 0x3c, 0xdc, 0x8b, 0x0b,
	0xca, 0x15, 0x24, 0xa4, 0x3f, 0xa0, 0x7a, 0xd6, 0xd4, 0xc0, 0xdf, 0x2c, 0x28, 0x8f, 0x12, 0xff,
	0xbb, 0x0d, 0xb9, 0xd1, 0x98, 0xbe, 0x23, 0xb1, 0xa7, 0xaa, 0xd8, 0xae, 0xb6, 0x50, 0x1b, 0x96,
	0x19, 0x3d, 0x17, 0xc3, 0xef, 0x53, 0x7d, 0x99, 0xb3, 0x38, 0x25, 0x58, 0x7f, 0xb3, 0x72, 0x99,
	0xaf, 0x89, 0xe8, 0x9d, 0xcd, 0x58, 0xe6, 0x77, 0x0b, 0x2a, 0x63, 0xcc, 0xe5, 0x1c, 0xa3, 0x0d,
	0xe8, 0x80, 0x09, 0x1a, 0x93, 0x9e, 0xf8, 0xeb, 0x53, 0xfa, 0x61, 0xc1, 0x4a, 0x26, 0xf9, 0x72,
	0x8e, 0x78, 0x0f, 0x0a, 0x46, 0x0c, 0x21, 0x98, 0xf7, 0x88, 0x20, 0xea, 0xba, 0xd8, 0xae, 0xfa,
	0x2d, 0xe7, 0x4b, 0x95, 0xce, 0x56, 0x4a, 0x97, 0x1a, 0xf8, 0x21, 0x14, 0x8c, 0x7b, 0xfc, 0x07,
	0x3d, 0xd5, 0x3b, 0xb3, 0x47, 0xa7, 0xff, 0x08, 0x72, 0xea, 0xfa, 0xc9, 0x82, 0x46, 0x86, 0xfa,
	0x8d, 0xb6, 0xa0, 0xe0, 0x51, 0xde, 0x8b, 0xfd, 0x48, 0xad, 0x28, 0xcd, 0x32, 0x5d, 0x78, 0x01,
	0x72, 0x9d, 0x20, 0x12, 0xef, 0x77, 0x3f, 0xe7, 0x20, 0x7f, 0xa4, 0xc6, 0x44, 0x1d, 0x98, 0x97,
	0xef, 0x01, 0xca, 0xdc, 0x71, 0x85, 0x72, 0x6a, 0xa6, 0xcb, 0x7c, 0x34, 0x70, 0xe5, 0xd3, 0xcf,
	0x5f, 0x5f, 0x6d, 0x40, 0x8b, 0xad, 0x64, 0xa7, 0xe5, 0xcb, 0xf4, 0x37, 0xb0, 0x34, 0x12, 0x7e,
	0xb4, 0x6e, 0x26, 0x4e, 0xbe, 0x21, 0x4e, 0xfd, 0x82, 0xa8, 0xe6, 0x5e, 0x51, 0xdc, 0x45, 0xac,
	0xb8, 0xa5, 0x8a, 0xb6, 0xad, 0x6d, 0xf4, 0x12, 0x16, 0xb5, 0x10, 0x73, 0xe4, 0x98, 0xf9, 0x59,
	0x79, 0x77, 0xae, 0x4f, 0x8d, 0x4d, 0xeb, 0x5a, 0x32, 0xa3, 0x1e, 0xc0, 0x58, 0xfe, 0x50, 0x7d,
	0x32, 0x39, 0xa3, 0xac, 0xce, 0xc6, 0x45, 0x61, 0x4d, 0xbf, 0xaa, 0xe8, 0x2b, 0xa8, 0xa4, 0xe9,
	0x6f, 0xa7, 0x12, 0x89, 0x5e, 0x41, 0x3e, 0xd5, 0x78, 0x74, 0xcd, 0x64, 0xc8, 0x3c, 0x0c, 0x8e,
	0x33, 0x2d, 0xa4, 0x89, 0xaf, 0x2a, 0xe2, 0x32, 0x2a, 0x0e, 0xfb, 0x6e, 0x7d, 0xf0, 0xbd, 0x8f,
	0x88, 0xc2, 0xe2, 0x50, 0x57, 0x51, 0x66, 0xee, 0x09, 0x41, 0x76, 0xd6, 0xa7, 0x07, 0x35, 0xfb,
	0x86, 0x62, 0xaf, 0x39, 0x2b, 0x19, 0xf6, 0x56, 0x2c, 0x71, 0x72, 0xf5, 0x04, 0x16, 0xb4, 0x6c,
	0x66, 0x37, 0x9f, 0x15, 0xe1, 0xec, 0xe6, 0x27, 0x74, 0x16, 0xd7, 0x55, 0x8d, 0x35, 0x8c, 0xb2,
	0x35, 0xe4, 0xdb, 0xdd, 0xb6, 0xb6, 0x8f, 0xf3, 0xea, 0xaf, 0xc9, 0x9d, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x77, 0xd7, 0xb1, 0x44, 0xd5, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SphereClient is the client API for Sphere service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SphereClient interface {
	// Info about this Sphere instance.
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error)
	// Create an environment.
	CreateEnv(ctx context.Context, in *CreateEnvRequest, opts ...grpc.CallOption) (*CreateEnvResponse, error)
	// List all environments.
	ListEnvs(ctx context.Context, in *ListEnvRequest, opts ...grpc.CallOption) (*ListEnvResponse, error)
	// List all environment models that can be created.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Gen an environment.
	GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error)
	// Reset an environment.
	ResetEnv(ctx context.Context, in *ResetEnvRequest, opts ...grpc.CallOption) (*ResetEnvResponse, error)
	// Step through an environment.
	StepEnv(ctx context.Context, in *StepEnvRequest, opts ...grpc.CallOption) (*StepEnvResponse, error)
}

type sphereClient struct {
	cc *grpc.ClientConn
}

func NewSphereClient(cc *grpc.ClientConn) SphereClient {
	return &sphereClient{cc}
}

func (c *sphereClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) CreateEnv(ctx context.Context, in *CreateEnvRequest, opts ...grpc.CallOption) (*CreateEnvResponse, error) {
	out := new(CreateEnvResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/CreateEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) ListEnvs(ctx context.Context, in *ListEnvRequest, opts ...grpc.CallOption) (*ListEnvResponse, error) {
	out := new(ListEnvResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/ListEnvs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error) {
	out := new(GetEnvResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/GetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) ResetEnv(ctx context.Context, in *ResetEnvRequest, opts ...grpc.CallOption) (*ResetEnvResponse, error) {
	out := new(ResetEnvResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/ResetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sphereClient) StepEnv(ctx context.Context, in *StepEnvRequest, opts ...grpc.CallOption) (*StepEnvResponse, error) {
	out := new(StepEnvResponse)
	err := c.cc.Invoke(ctx, "/sphere.api.Sphere/StepEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SphereServer is the server API for Sphere service.
type SphereServer interface {
	// Info about this Sphere instance.
	Info(context.Context, *Empty) (*InfoResponse, error)
	// Create an environment.
	CreateEnv(context.Context, *CreateEnvRequest) (*CreateEnvResponse, error)
	// List all environments.
	ListEnvs(context.Context, *ListEnvRequest) (*ListEnvResponse, error)
	// List all environment models that can be created.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Gen an environment.
	GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error)
	// Reset an environment.
	ResetEnv(context.Context, *ResetEnvRequest) (*ResetEnvResponse, error)
	// Step through an environment.
	StepEnv(context.Context, *StepEnvRequest) (*StepEnvResponse, error)
}

// UnimplementedSphereServer can be embedded to have forward compatible implementations.
type UnimplementedSphereServer struct {
}

func (*UnimplementedSphereServer) Info(ctx context.Context, req *Empty) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedSphereServer) CreateEnv(ctx context.Context, req *CreateEnvRequest) (*CreateEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnv not implemented")
}
func (*UnimplementedSphereServer) ListEnvs(ctx context.Context, req *ListEnvRequest) (*ListEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvs not implemented")
}
func (*UnimplementedSphereServer) ListModels(ctx context.Context, req *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (*UnimplementedSphereServer) GetEnv(ctx context.Context, req *GetEnvRequest) (*GetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnv not implemented")
}
func (*UnimplementedSphereServer) ResetEnv(ctx context.Context, req *ResetEnvRequest) (*ResetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetEnv not implemented")
}
func (*UnimplementedSphereServer) StepEnv(ctx context.Context, req *StepEnvRequest) (*StepEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StepEnv not implemented")
}

func RegisterSphereServer(s *grpc.Server, srv SphereServer) {
	s.RegisterService(&_Sphere_serviceDesc, srv)
}

func _Sphere_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_CreateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).CreateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/CreateEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).CreateEnv(ctx, req.(*CreateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_ListEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).ListEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/ListEnvs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).ListEnvs(ctx, req.(*ListEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/GetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).GetEnv(ctx, req.(*GetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_ResetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).ResetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/ResetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).ResetEnv(ctx, req.(*ResetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sphere_StepEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphereServer).StepEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphere.api.Sphere/StepEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphereServer).StepEnv(ctx, req.(*StepEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sphere_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sphere.api.Sphere",
	HandlerType: (*SphereServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Sphere_Info_Handler,
		},
		{
			MethodName: "CreateEnv",
			Handler:    _Sphere_CreateEnv_Handler,
		},
		{
			MethodName: "ListEnvs",
			Handler:    _Sphere_ListEnvs_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Sphere_ListModels_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _Sphere_GetEnv_Handler,
		},
		{
			MethodName: "ResetEnv",
			Handler:    _Sphere_ResetEnv_Handler,
		},
		{
			MethodName: "StepEnv",
			Handler:    _Sphere_StepEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/env.proto",
}
